services:
  - type: web
    name: aceminibot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false           # fill in on Render
      - key: WEBHOOK_SECRET
        generateValue: true   # Render makes one for you, or set your own
      - key: DATABASE_URL
        sync: false           # paste from Neon
